//Nombre de la aplicacion
spring.application.name=crud-usuarios-ryudevcode

//Configuracion de la base  de datos H2
spring.datasource.url= jdbc:h2:mem:ryudevcode_bd 
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

//Indica  a hibernate que base  de datos utilizara
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

//muestra las consultas SQL en la consola
spring.jpa.show-sql=true

//Da formato a las consultas SQL para que sea faciles de leer
spring.jpa.properties.hibernate.format_sql=true

//crea o actuliza automaticamente las tablas 
spring.jpa.hibernate.ddl-auto=update

//activa la consola web h2
spring.h2.console.enabled=true

//ruta para acceder ala consola
spring.h2.console.path=/h2-console

